### ISSUE TITLE
关于 octavia 等云提供商的 LB 来负载 master

### ISSUE THREAD

**Issue by gongzili456** [lingxiankong/kubernetes_study#1]
因为对 Python 不太熟悉，没有找到 octavia 相关配置，能否指点一二？

**Comment by lingxiankong** [comment]
不需要特殊配置，调用 octavia 创建 LB 即可：https://github.com/lingxiankong/kubernetes_study/blob/HEAD/installation/ansible/version_4/site.yml#L134

**Comment by gongzili456** [comment]
我的疑问在于 LB 的 https 证书是在哪个阶段如何生成的。

**Comment by lingxiankong** [comment]
我没有用 TLS termination，https 还是在 api server 验证，第一个 master 初始化时不就能够自动生成证书么。

**Comment by gongzili456** [comment]
我是在 AWS 上做的实验，预先配置一个 ELB（Elastic Load Balancing）需要针对 EC2 主机做端口转发，如果是 HTTPS 协议就需要配置证书，然后才能拿到 VIP，但是 kubeadm init 的时候就需要这个 VIP，而 ELB 需要的证书是 init 阶段才生成的，这里就比较矛盾了。

**Comment by gongzili456** [comment]
openstack 的 LB 不需要配置https转发规则吗？

**Comment by lingxiankong** [comment]
朋友，你再看看我的 ansible 脚本，看创建 lb/listener/pool/member 时那些参数，我配置的是 TCP，不是 HTTPS
